name: financialresume
description: An inteligent application for financial tracking.
version: 2.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  permission_handler: ^11.0.0
  pdf: ^3.11.3
  open_file: ^3.3.2
  intl: 0.20.2
  photo_view: ^0.15.0
  share_plus: ^10.0.0
  google_mlkit_text_recognition: ^0.15.0
  image: ^4.5.4
  uuid: ^4.5.1
  camera: ^0.11.2
  google_sign_in: ^6.2.1
  printing: ^5.13.3
  google_generative_ai: ^0.4.0
  shared_preferences: ^2.3.2
  mailer: ^6.5.0
  google_fonts: ^6.2.1
  url_launcher: ^6.1.11
  provider: ^6.1.1
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  package_info_plus: ^4.2.0
  flutter_svg: ^2.0.9
  flutter_secure_storage: ^9.2.1
  http: ^1.2.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_24pt-Regular.ttf
        - asset: assets/fonts/Inter_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_28pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_28pt-Bold.ttf
          weight: 700

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/app_logo.svg

flutter_icons:
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_logo2.png
  android_gravity: center
  ios_content_mode: center

  android_12:
    color: "#ffffff"
    image: assets/images/app_logo2.png
    android_gravity: center




