// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK2xMB0EuJ6LILisW0d6fjZpbHV6WGWUk',
    appId: '1:129167047675:android:615799635e252330c7e95e',
    messagingSenderId: '129167047675',
    projectId: 'financialresume0',
    storageBucket: 'financialresume0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_SeLJottc6jCh3tvRcJ_1X3obXMbU_XI',
    appId: '1:129167047675:ios:af574704222243d6c7e95e',
    messagingSenderId: '129167047675',
    projectId: 'financialresume0',
    storageBucket: 'financialresume0.firebasestorage.app',
    androidClientId: '129167047675-b8fdmk8g0n33gdgv9i43n60lsr92876e.apps.googleusercontent.com',
    iosClientId: '129167047675-8tj6vn3mjoq628jg4s2vc1ojhk9st0ve.apps.googleusercontent.com',
    iosBundleId: 'com.example.financialresume',
  );
}
